name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Extract GitHub Tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Validate SemVer Format
        run: |
          echo $GITHUB_ENV
          SEMVER_REGEX="[0-9]+\.[0-9]+\.[0-9]+$"

          if [[ ! $TAG =~ $SEMVER_REGEX ]]; then
            echo "❌ Tag '$TAG' is not a valid SemVer format (X.Y.Z)."
            exit 1
          fi

          echo "✅ Tag '$TAG' is valid!"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Commit Messages
        id: commit_message
        run: |
          export COMMITS=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)
          echo "commit_message=$COMMITS" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions.
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.commit_message }}
          draft: false
          prerelease: false
