name: Create Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    name: Create Release
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Commit Messages
        id: commit_message
        run: |
          export COMMITS=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)
          echo "commit_message=$COMMITS" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions.
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.commit_message }}
          draft: false
          prerelease: false
